backend:
  name: git-gateway
  branch: experimental
media_folder: "/sources"
collections:
  - name: "radio"
    label: "Test"
    folder: "equipment/radio"
    fields:
      - {label: "Title", name: "title", widget: "string"}