backend:
  name: git-gateway
  branch: experimental
media_folder: "/sources"
collections:
  - name: "radio"
    label: "Radio"
    folder: "equipment/radio"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Test", name: "rating", widget: "number"}